version: "3.9"
services:
  expressapp:
    container_name: expressapp
    build: ./intervention
    expose:
      - 3000
    volumes:
      - ./intervention:/usr/src/app
  reactapp:
    container_name: reactapp
    build: ./interventionFront
    expose:
      - 3005
    volumes:
      - ./interventionFront:/usr/src/app
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - expressapp
      - reactapp
    restart: always
