version: "3.9"
services:
  expressapp:
    container_name: expressapp
    build: ./intervention
    expose:
      - 3000
    volumes:
      - ./intervention:/usr/src/app
  reactapp:
    container_name: reactapp
    build: ./interventionFront
    expose:
      - 3005
    volumes:
      - ./interventionFront:/usr/src/app
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - expressapp
      - reactapp
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhostd:/etc/nginx/vhost.d
      - html:usr/share/ningx/html
volumes:
  certs:
  html:
  vhostd:
